### ISSUE TITLE
Transformation functions for 3x3/3x2 matrices (2d matrices)

### ISSUE THREAD

**Issue by WebFreak001** [Dav1dde/gl3n#57]
It would be nice to have rotate, translate and scale in 2d aswell

**Comment by Extrawurst** [comment]
afaik they apply on mat3 awell:
```
static if((rows == cols) && (rows >= 3)) {
        static if(isFloatingPoint!mt) {
            /// Returns an identity matrix with an applied rotate_axis around an arbitrary axis (nxn matrices, n >= 3).
            static Matrix rotation(real alpha, Vector!(mt, 3) axis) {......
``` 
see:
https://github.com/Dav1dde/gl3n/blob/master/gl3n/linalg.d#L1444

**Comment by Dav1dde** [comment]
A 2x2 rotation matrix is indeed missing, not sure how useful it would be (but I wouldnt be against adding it anyways), since you normally work with homogeneous coordinates anyways (correct me if I am wrong!). 3x3 rotation matrices are supported (as @Extrawurst stated), 3x2 aren't, if you give me a good resource why they are needed and what they do, I am all for adding them.

**Comment by WebFreak001** [comment]
There is D2D1_MATRIX_3X2 in Direct2D for 2D transformation.

https://msdn.microsoft.com/en-us/library/windows/desktop/dd368132%28v=vs.85%29.aspx

**Comment by Dav1dde** [comment]
Ok, but why is it important to have a 3x2 matrix, instead of a 3x3. How does it work? I was looking for something more mathematical, since I've never seen a use for a 3x2 matrix.

**Comment by WebFreak001** [comment]
Not mathematical but it saves 12 bytes in ram for each matrix

**Comment by Dav1dde** [comment]
Which is irrelevant. You don't create millions of matrices and keep these in memory.
