### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by marler8997** [Dav1dde/gl3n#76]
It looks like this repo has not been modified since January.  Is that because the code is stable and works well, or because the project is dead, or maybe just that no one is using it?  I'm doing some OpenGL work in D and wanted to use an existing library for GLM instead of writing my own.  In your opinion, is this the right project to go with, or another project?

**Comment by Dav1dde** [comment]
The code exists since late 2011,  it is quite stable. Issues that come up I usually fix relativly quickly (important ones). Other than that the Project could use some organizing, but that's it.

People are using the project and some are working on it (adding awesome things! SIMD -> https://github.com/Dav1dde/gl3n/issues/75).

Depending on what you need, if it is Vectors, Quaternions, Matrices, some interpolation and utility functions (e.g. lot's of GLSL funcs) it's the right choice.

**Comment by marler8997** [comment]
Thanks for the quick response.  Based on what you said I'll give this library a try.
